apiVersion: v1
kind: Service
metadata:
  name: #deployName#-svc
  labels:
    app: #deployName#r
spec:
  selector:
    app: #deployName#
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
    - protocol: TCP
      targetPort: 9999
      port: 9999
      name: #deployName#-svc-9999
  type: ClusterIP
  clusterIP: None