apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #deployName#
    lateinos-apptype: openresty
    deploy-code-type: #codeType#
    deploy-base-template: #deployBaseTemplate#
  name: #deployName#-deploy
  namespace: #deployNamespace#
spec:
  replicas: #deployReplicas#
  selector:
    matchLabels:
      argocd-app-name: #deployName#-deploy
      argocd-app-namespace: #deployNamespace#
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: 80,443
        traffic.sidecar.istio.io/includeInboundPorts: '*'
      labels:
        app: #deployName#
        argocd-app-name: #deployName#-deploy
        argocd-app-namespace: #deployNamespace#
        lateinos-apptype: openresty
        deploy-code-type: #codeType#
        deploy-base-template: #deployBaseTemplate#
        image-tag: to-replace
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: ' -server -Xms256m -Xmx256m'
            - name: JAVA_ARGS
          image: #deployImage#
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /v1/heartbeat/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: #deployName#
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /v1/heartbeat/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: #nginxLogDir#
              name: log-mount
          resources:
            limits:
              cpu: 2
              memory: 1.5Gi
            requests:
              cpu: 0.5
              memory: 1.5Gi
      dnsPolicy: ClusterFirst
      hostIPC: true
      volumes:
        - hostPath:
            path: /data/logcollector/nginx/#deployName#
            type: ''
          name: log-mount