apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #deployName#
    lateinos-apptype: daemon
    deploy-code-type: #codeType#
    deploy-base-template: #deployBaseTemplate#
  name: #deployName#-deploy
  namespace: #deployNamespace#
spec:
  replicas: #deployReplicas#
  selector:
    matchLabels:
      argocd-app-name: #deployName#-deploy
      argocd-app-namespace: #deployNamespace#
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: #deployName#
        argocd-app-name: #deployName#-deploy
        argocd-app-namespace: #deployNamespace#
        lateinos-apptype: daemon
        deploy-code-type: #codeType#
        deploy-base-template: #deployBaseTemplate#
        image-tag: to-replace
    spec:
      containers:
        - env:
            - name: RT_ASYNCTASK_SCHEDULE_CODE
              value: '#scheduleCode#'
            - name: JAVA_OPTS
              value: ' -server'
            - name: JAVA_ARGS
          image: #deployImage#
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /v1/heartbeat/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: #deployName#
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /v1/heartbeat/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              memory: 0.5Gi
              cpu: '0.05'
            limits:
              memory: 1Gi
              cpu: '1'
      dnsPolicy: ClusterFirst
      hostIPC: true
      restartPolicy: Always
